sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '0000'     # 密码记得加‘’ 这就是字符串的含金量  我真是阐述你的梦
